- libmemcached/auto.cc
- tests/mem_functions.cc
- tests/parser.cc
Make test 시 fail 되던 테스트 케이스들을 수정하였습니다.
- `memcached_inc/decrement_with_initial_by_key()` 가 `MEMCACHED_PROTOCOL_ERROR`를 리턴하지 않고, `binary_incr_decr()` 함수를 호출하여 결과를 돌려주도록 수정
- test collection 'regression' 의 'fail' 테스트 케이스를 테스트 목록에서 제외 (ARCUS 는 binary protocol 을 fully 지원하지 않음)
- 특정 테스트 케이스 판정 부분의 `__APPLE__` 매크로 구분을 삭제.
@jhpark816 @whchoi83 구두로 논의 후에 수정하고 PR 보낸 것이긴 하지만, 일단 리뷰...해... 주십사 하고 멘션 답니다 ㅋ
> Fixed failed unit tests.

- .travis.yml
@jhpark816 
travis-ci 환경인 ubuntu 14.04 에서는
test에 대한 결과 파일인 test-suite.log를 생성 합니다.
test실패 했을 때 실패에 대한 내용을 한번에 알 수 있도록
test-suite.log 내용을 출력하는 코드를 추가 했습니다.
> CLEANUP: print travis-ci test log

- libmemcached/connect.cc
- libmemcached/get.cc
- libmemcached/server.cc
- libmemcached/server.h
- libmemcached/version.cc
- libmemcached/version.h
- tests/mem_functions.cc
Reviewer
서버 version 정보를 조회 및 저장하고
multiple get operation에 대한 optimize 가능 여부를 판단해서
n개의 get operation으로 나누어 보내도록 할 수 있도록 수정 한 PR 입니다.
확인 요청 드립니다.
code tag : OPTIMIZE_MGET
> CLEANUP: enable optimize mget operation with instance version

- libmemcached/collection.cc
Reviewer
기존에 comma-separating 으로 n개의 key(mkey)를
구분하던 방식에서 space-separating 으로 구분할 수 있도록
변경하는 PR입니다. 확인 요청 드립니다.
> CLEANUP: Change from comma-separating to space-separating

- libmemcached/include.am
Makefile에서 server_instance header file
추가 부분이 빠져있어서 추가 했습니다.
> FIX: Makefile error due to include header

- docs/07-btree-API.md
- tests/mem_functions.cc
최신 arcus-memcached의 bop smget 스펙 변경으로,
smget에 참여하는 btree의 maxcount, overflowaction, maxbkeyrange attribute 설정이
모두 같아야 하는 제약이 제거되면서 ATTR_MISMATCH 관련 부분을 제거 했습니다.
server response parsing 하는 부분의 코드는 그대로 남겨 둔 상태로,
old version arcus-memcached를 대응할 수 있습니다.
@jhpark816 
확인 요청 드립니다.
> FIX: Removed the ATTR_MISMATCH test according to the spec change of "bop smget"

- libmemcached/collection.cc
collection 속성 중 type과  readable이 제대로 반환되지 않음.
1. type이 항상 null이 반환되는 문제
: type 비교시에 끝 구분 문자열(\r\n)을 고려하지 않아 모든 collection type이 null이 반환됨.
ex) compare(kv == kv\r\n) => false
2. readable 처리 코드가 없어 항상 false가 반환됨
Reviewer
- develop branch로 rebase 했습니다.
> FIX : Get collection attributes(type, readable)

- libmemcached/dump.cc
- tests/mem_functions.cc
stats cachedump command format :
stats cachedump <slab_clsid> \<limit> [ forward | backward [sticky] ]\r\n
slab_clsid의 범위는 0 ~ 200이며, 수행방향은 forward나 backward로 지정하게 됩니다.
현재 c-client의 cachedump는 slab_clsid가 200 ~ 255까지 수행되서 CLIENT_ERROR illegal slab id와 명령어의 수행방향 인자값이 0으로 들어가 있어 CLIENT_ERROR BAD COMMAND FORMAT를 받게 됩니다.
dump test에선 실패 시 반환값이 적절하지 않아 dump 기능이 제대로 검사되지 않았습니다.
commit 내역 요약:
- slab_clsid의 최대 수행범위를 255에서 200으로 수정.
- 명령어 수행방향 인자값 0을 생략(수행방향 default는 forward)
- dump_test()에서 confirm_key_count() 결과값이 ULONG_MAX이 아닌지 확인하도록 수정.
Reviewer
> FIX: stats cachedump bug

- libmemcached/memcached.cc
replication enabled 일 때 rgroup list만 free하도록 수정 했습니다.
@jhpark816 
확인 요청 드립니다.
> FIX: if replication is enabled, only free rgroup lists

- libmemcached/arcus.cc
ZK event에 의해 update cache list 로직이 수행 될 경우,
실제 cache list가 변경 된 경우에만 pool repopulate를 수행도록 수정 했습니다.
pool repopulate 동작은 오버헤드가 큰 동작으로,
현재 수행 비용이 부담되는 상태이기 때문에 실제로 필요 할 때만 수행하도록 최적화 하기 위한 수정 입니다.
@jhpark816 
확인 요청 드립니다.
> ENHANCE: if changed in the cache list, repopulate the pool

- libmemcached/constants.h
- libmemcached/continuum.hpp
- libmemcached/hash.cc
- libmemcached/hosts.cc
- libmemcached/memcached.cc
- libmemcached/memcached.h
- libmemcached/types.h
- libmemcached/util/pool.cc
- libmemcached/util/pool.h
- tests/ketama.cc
pool 을 사용하는 상태에서, cache list 변경이 발생하면
pool의 모든 memcached_st hash ring update 지연시간 동안
서비스하지 못하는 상태가 지속된다. pool size가 크고 cluster를 구성하는
cache instance 수가 많을 경우 문제가 될 수 있다.
pool을 사용 할 경우 master memcached_st의 hash ring 의 pointer를
pool의 모든 memcached_st가 공유해서 사용하도록 최적화 한다.
pool fetch, release 단계에서는 항상 pool->mutex lock을 획득 한 상태로 동작하므로,
master memcached_st의 hash ring은 pool->mutex lock hold 상태에서 교체 한다.
모든 hash ring은 reference count를 두고 0이 되면 memory를 free 한다.
- master는 cache list update가 발생하면, 새로운 cache list hash ring을 생성하고, refcount=1로 설정해
pool->mutex lock 상태에서 기존 hash ring release & new hash ring으로 교체 를 수행한다.
- pool fetch는 pool->mutex lock 상태에서 master의 hash ring pointer를 copy 하고 refcount += 1 한다.
- pool release는 pool->mutex lock 상태에서 hash ring pointer의 refcount -= 1 하고, 0 이면 memory free 한다.
- …
> ENHANCE: optimized reflection of cache list changes

- libmemcached/arcus.cc
cachelist update 동작 중 memcached_pool_repopulate() 동작을
pool의 memcached_st가 수행할 수 있었던 상황을 회피하기 위해
master memcached_st만 repopulate를 할 수 있도록 조건 추가 했습니다.
@jhpark816 
확인 요청 드립니다.
> CLEANUP: added master check when pool repopulate from cachelist update

- libmemcached/get.cc
connection 실패로 MEMCACHED_ERRNO error 가 발생했을 때
assertion fail 시키지 않도록 하기 위한 PR 입니다.
@jhpark816 
확인 요청 드립니다.
> CLEANUP: do not assertion fail on connection failure

- libmemcached/protocol/protocol_handler.c
codacy 에 다음과 같은 오류가 나와서 수정 PR을 보냅니다.
```
Returning/dereferencing 'ret' after it is deallocated / released
```
> FIX: removed possibility of returning deallocated pointer

- config/version.pl
- configure.ac
https://github.com/jam2in/arcus-memcached-EE/issues/869 c client의 version 관리 방법 변경을 위한 PR 입니다.
기존의 arcus-c-client는 version이 release 되면 직접 configure.ac의 ARCUS_VERSION_STRING 값을 변경해주어야 했습니다. 이러한 관리 포인트를 줄이기 위해 m4 file로 생성하는 version 정보를 이용하여 c client version을 생성하도록 변경합니다.
m4 file로 생성하는 version 정보는 libmemcached version을 포함하며 아래와 같이 client info에 생성됩니다.
`<host>_<addr>_<pool-size>_c_<1.10.3_10>_<20200204135808_16e344388040055>`
기존에 생성되던 정보에서 "1.10.3_10" 부분이 변경된 부분이며 기존에는 "1.10.3"만 표시되었습니다.
변경 부분의 의미는 `c client version _ head 이후 commit 개수` 입니다.
@jhpark816 
확인 요청 드립니다.
> CLEANUP: change to create version using m4 file

- libmemcached/collection.h
arcus-memcached의 max element bytes 변경에 따라
MEMCACHED_COLL_MAX_ELEMENT_SIZE macro 값을 16K로 변경했습니다.
MEMCACHED_COLL_MAX_ELEMENT_SIZE macro는 unit test 중
max element bytes test 에서 사용하고 있습니다.
- MEMCACHED_COLL_MAX_ELEMENT_SIZE+1 만큼 value insert/update 요청하여 error가 return 되는지 확인 합니다.
@jhpark816 
확인 요청 드립니다.
> CLEANUP: change max element bytes

- docs/07-btree-API.md
#66 관련 PR 입니다.
eflagFilter 구조체에서 compare value를 최대 100개까지 지정할 수 있으며
`memcached_coll_eflags_filter_init()` API를 제공하지만, document에 소개되어 있지 않아
document에 관련 내용을 추가 했습니다.
@jhpark816 
확인 요청 드립니다.
> DOC: add multi eflag filter description

- libmemcached/memcached.cc
- libmemcached/memcached.h
- libmemcached/util/pool.cc
pool 사용 시 master_mc 객체에 대해 free할 수 없도록 하기 위한 PR 입니다.
#51 다음 PR입니다.
memcached_st 객체 내부 state에 is_pool_master 라는 변수를 추가했고, true로 세팅되어 있을 경우 free할 수 없도록 했습니다.
is_pool_master 변수는 memcached_pool_create() 호출 시 master_mc 객체에 true로 세팅,
memcached_pool_destory() 호출 시 master_mc 객체에 false로 세팅 하는 방식으로 동작합니다.
@jhpark816 
확인 요청 드립니다.
> FIX: prevent master_mc from being freed while using pool

- libmemcached/arcus.cc
- libmemcached/arcus_priv.h
#72 관련 PR 입니다.
기존 `arcus->is_initializing` 변수는 zookeeper 초기화를
기다리는 목적으로만 되었습니다.
사용 목적에 따라서 `arcus_zk_st`로 옮기는게 맞는것 같아
`arcus->zk.is_initializing`으로 사용하도록 변경 하였습니다.
변수가 이동됨에 따라 zookeeper close 하는 부분에서 초기화를 진행하도록 수정 했습니다.
arcus_close(), arcus_pool_close(), arcus_proxy_close() 모두 do_arcus_zk_close()를 호출하여
close 작업을 진행하므로 do_arcus_zk_close() 에서만 초기화 해주면 됩니다.
@SuhwanJang @jhpark816 
확인 요청 드립니다.
> CLEANUP: move the initializing to zk_st depending on usage

- .travis.yml
[서버 PR 446](https://github.com/naver/arcus-memcached/pull/446/commits/303d794214fd169a02f30af5eb39d9239ca020b3)처럼 noti 조건을 변경했습니다.
기존의 조건: forked repo가 아닐 때에만 noti
변경된 조건: forked repo가 아니거나, PR을 했을 때에만 noti
> FIX: enable email notification for pull request

- libmemcached/response.cc
response string의 특정 문자를 비교하는 방식 대신 memcmp를 활용하는 방식으로 리팩토링 하였습니다.
특정 response가 다른 response의 부분 문자열인 경우, 비교 순서를 더 뒤로 늦췄습니다. (예) ATTR과 ATTR_MISMATCH
> CLEANUP: refactor 'textual_read_one_coll_response' functions

- libmemcached/response.cc
cache server에서 pipe 연산 중 SWITCHOVER or REPL_SLAVE 이 발생하면 pipe_error를 반환.
client는 위 에러 발생 시, END를 기대하고 있는 버그가 있어서 수정하였습니다.
> FIX: pipe operation is stopped if switchover is done.

- libmemcached/collection.cc
- libmemcached/response.cc
bop count, position 명령의 파싱 위치를 memcached_coll_response로 바꾸었습니다.
memcached_read_one_coll_response를 호출하기 전, 명령이 bop count이거나 bop position인지 체크합니다. 해당 명령이면 직접 response를 읽어 결과를 리턴합니다.
> CLEANUP: parse 'bop count' and 'bop position' in memcached_coll_response()

- libmemcached/response.cc
KEY_TOO_BIG 에러는 response 에서 발생하지 않는 에러여서 제거하였습니다.
history를 보니 initial commit 때부터 있었는데 실수로 들어간 것으로 보입니다.
> CLEANUP: don't occur KEY_TOO_BIG error in response.

- libmemcached/purge.cc
- libmemcached/stats.cc
- libmemcached/version.cc
response 쪽에서 에러 발생 시 io_reset을 수행하는데도 불구하고 io_reset을 중복으로 호출하는 부분 제거하였습니다.
//response 쪽에서 에러 발생 시 io_reset을 수행
```
memcached_return_t memcached_read_one_response(memcached_server_write_instance_st ptr,
char *buffer, size_t buffer_length,
memcached_result_st *result)
{
...
if (ptr->root->flags.binary_protocol)
{
rc= binary_read_one_response(ptr, buffer, buffer_length, result);
}
else
{
rc= textual_read_one_response(ptr, buffer, buffer_length, result);
}
unlikely(rc == MEMCACHED_UNKNOWN_READ_FAILURE or
rc == MEMCACHED_PROTOCOL_ERROR or
rc == MEMCACHED_CLIENT_ERROR or
rc == MEMCACHED_PARTIAL_READ or
rc == MEMCACHED_MEMORY_ALLOCATION_FAILURE)
memcached_io_reset(ptr);
return rc;
}
```
> CLEANUP: remove calling memcached_io_reset in duplicate.

- libmemcached/arcus.cc
- libmemcached/arcus.h.in
- libmemcached/arcus_priv.h
현재 zookeeper event 처리를 zookeeper client의
completion thread가 담당하는 동작으로 인해 SESSION_EXPIRED 처리 도중
에러가 발생하면 zookeeper client만 종료되어 event를 받지 못한다는 문제가 있는 상태입니다.
이러한 문제를 해결하기 위해 zookeeper event 처리를 담당하는 별도의 daemon thread를 두고
daemon thread가 모든 zookeeper event 처리를 담당하도록 수정하기 위한 PR 입니다.
@minkikim89 @hjyun328 리뷰 요청 드립니다.
> CLEANUP: add arcus_zk_manager for process requests of ZooKeeper

- libmemcached/response.cc
object too large for cache를 CLIENT_ERROR 로도 받도록 수정하였습니다.
> CLEANUP: changed E2BIG error as CLIENT_ERROR

- libmemcached/constants.h
- libmemcached/response.cc
- libmemcached/server.cc
- libmemcached/server.h
- libmemcached/server.hpp
- tests/mem_functions.cc
**delayed reconnect cases**
- 네트워크 순단 문제
- client 단 error
**immediate reconnect cases**
- server error response (ERROR, CLIENT_ERROR, SERVER_ERROR)
* ERROR, CLIENT_ERROR 에 경우 Connection 상에 잔여 데이터가 있을 수 있어 cleanup 필요
* SERVER_ERROR 에 경우 응용에게 service unavalable 응답을 보내는 것보다 out of memory 오류를 넘기는 것이 나음. 네트워크 순단 문제와 달리 빠른 응답이기 때문에 응용의 작업 스레드가 증가될 요인도 없다.
- client 단 response partial failure (client - server protocol 이 다른 상태)
**no reconnect cases**
- no error (END, NOT_FOUND, TYPE_MISMATCH ..)
- E2BIG
**cilent 단 error code**
- MEMCACHED_UNKNOWN_READ_FAILURE : 알 수 없는 에러코드가 오는 경우 or network bytes read failure.
- MEMCACHED_PROTOCOL_ERROR : ERROR response 받은 경우 or 읽은 문자열이 프로토콜이 틀린 경우(ex \n이 없는 경우).
- MEMCACHED_CLIENT_ERROR : CLIENT_ERROR response
- MEMCACHED_SERVER_ERROR : SERVER_ERROR response
- …
> FEATURE: immediate reconnect according to error response.

- libmemcached/response.cc
컴파일 시에 보여주는 fix embedding a directive within macro argument 경고 메세지를 해결하기 위한 PR입니다.
macro argument(unlikely)에 directive(#ifdef~#endif) 사용하지 않도록 수정하였습니다.
> FIX: fix embedding a directive within macro argument

- libmemcached/io.cc
connection disconnect되어 recv() 리턴 값이 0 나온 경우의 에러코드를 MEMCACHED_CONNECTION_FAILURE로 변경하였습니다.
> CLEANUP: set MEMCACHED_CONNECTION_FAILURE when server has disconnected.

- libmemcached/response.cc
immediate reconnect about UNKNOWN_READ_FAILURE
MEMCACHED_UNKNOWN_READ_FAILURE 에러가 발생하는 경우는
- client 가 기대하는 server response가 오지 않은 경우 : protocol 차이일 뿐이므로 immediate reconnect
- socket error(recv < 0)의 응용 오류 코드. 에를 들어 recv() 에서 EXXX 에러 발생한 경우 이를 그대로 응용에게 전달하지 않고, MEMCACHED_UNKNOWN_READ_FAILURE로 전달. 이 경우에 io 모듈단에서 delayed reconnect 하도록 되어 있음.
> FEATURE: immediate reconnect about UNKNOWN_READ_FAILURE

- libmemcached/response.cc
collection item 과 동일한 key 로 kv item 저장 요청하면,
TYPE_MISMATCH 가 발생합니다.
```
set c-m001:testkey-17 0 0 3
qwe
TYPE_MISMATCH
```
kv response 모듈에서 TYPE MISMATCH 핸들링이 안되어 있어서
UNKNOWN_READ_FAILURE를 반환 & 이로 인해 connection reconnect하게 되는 버그를 수정하였습니다.
> FIX: handled TYPE_MISMATCH in kv response

- docs/03-key-value-API.md
doc 문서의 Value 설명 부분이 잘못되어
이에 대한 수정을 위한 PR 입니다.
기존 문서 에서 `Value는 최대 1Mb까지 저장할 수 있다.`로 설명된 부분을
`Cache item의 최대 크기는 1MB이다.`로 변경 했습니다.
@jhpark816 
확인 요청 드립니다.
> DOC: change the description of the max item size

- docs/01-arcus-cloud-basics.md
- docs/02-arcus-c-client.md
- docs/03-key-value-API.md
- docs/04-list-API.md
- docs/05-set-API.md
- docs/06-map-API.md
- docs/07-btree-API.md
- docs/08-attribute-API.md
- docs/09-other-API.md
- docs/10-appendix.md
문서시스템에서 최상단 제목을 H1(# 한 개)보다 낮게 설정할 경우, 다음과 같이 문서 제목이 사이드 바의 목차에 보이는 현상이 있습니다.
(문서의 최상단 제목인 Key-Value Item이 목차에 표시 됨)
이 현상을 해결하기 위해 제목의 레벨을 하나씩 올렸습니다.
> DOC: decrease header level to improve document system's UI

- docs/02-arcus-c-client.md
- docs/03-key-value-API.md
- docs/05-set-API.md
- docs/09-other-API.md
문서시스템에서 다음과 같이 문법 하이라이팅이 이루어지지 않는 버그가 있습니다. 
문법 하이라이팅을 위해 코드 블록에 어떤 언어인지 힌트를 주는데, C가 대문자로 입력된 것이 원인입니다. 
이 패치를 적용할 경우 다음과 같이 바뀝니다.
> DOC: fix syntax highlighting

- libmemcached/response.cc
할당받은 메모리 영역을 넘어서 접근하는 버그를 수정하였습니다.
> FIX: fix unallocated memory access in mkey fetch

- libmemcached/common.h
- libmemcached/storage.cc
기존 storage.cc 의 memcached_send_ascii() 함수는 코드가 복잡하고, 고정 버퍼를 사용하여 command string 을 만드는 방식은 버퍼 크기가 필드 길이에 의존하는 문제를 갖고 있어서 리팩토링 하였습니다.
- key length limit 변경 또는 옵션 필드가 추가될 때마다 버퍼 크기 변경이 필요하게 됨.
최신 libmemcached code 를 포팅하였고, 기존 동작의 로직은 그대로 유지하게끔 수정하였습니다.
> CLEANUP: refactored memcached_send_ascii() in storage.cc

- libmemcached/constants.h
- libmemcached/fetch.cc
- libmemcached/response.cc
- tests/mem_functions.cc
key 최대 길이 제한을 4K로 변경하였습니다. (issue : https://github.com/naver/arcus-c-client/issues/121)
수정 사항
- key max length macro(MEMCACHED_MAX_KEY) 값 변경
- response string copy buffer 크기 증가. (in fetch.cc)
- get 종류 명령의 응답은 first line 에 key string 을 포함되어 있음.
- long key test 코드 추가
- simple kv set / get
- smget 1.9v
> FEATURE: increased max key length : 250 => 4K.

- libmemcached/collection.cc
- libmemcached/collection.h
- libmemcached/dump.cc
- libmemcached/flush.cc
- libmemcached/stats.cc
snprintf 관련 코드를 리팩토링하였습니다.
- 한 함수 내에서 macro 를 여러번 사용하는 곳에서는 변수에 할당하여 사용하도록 변경.
```
MEMCACHED_DEFAULT_COMMAND_SIZE
MEMCACHED_MAXIMUM_COMMAND_SIZE
```
- 아래와 같은 패턴으로 사용하도록 수정
```
snprintf(buffer, buffer_length, ...)
snprintf(buffer + write_length, buffer_length - write_length, ...)
```
- error handling 추가
```
if ((size_t)write_length >= buffer_length || write_length < 0)
{
return memcached_set_error(*ptr, MEMCACHED_MEMORY_ALLOCATION_FAILURE, MEMCACHED_AT,
memcached_literal_param("snprintf(MEMCACHED_DEFAULT_COMMAND_SIZE)"));
}
```
> CLEANUP: refactored snprintf codes

- tests/mem_functions.cc
noreply_test() 함수에서 no_reply 연산이 아닌 경우에 no_reply unset 후 수행하도록 수정하였습니다.
- 최신 libmemcached 는 현재 c-client 와 같이 되어있긴 합니다.
- 위 테스트 함수가 수정되지 않으면, get 함수에서 memcached_vdo() 함수를 사용할 수 없습니다. (get, mget 분리시에 처리할 예정)
- memcached_vdo() 사용하는 경우, no_reply 설정된 상태여서 response count 증가되지 않아 조회 결과를 얻을 수 없어 테스트 실패합니다.
> FIX: unset noreply before get operation in noreply_test().

- libmemcached/purge.cc
memcached_purge() 함수 리턴 전에 flag 를 false 로 세팅하는 것이 맞아보입니다.
> FIX: set purge recursion flag to false before return

- libmemcached/io.cc
io_flush() 에서 poll timeout 발생에 대한 처리 검토(https://github.com/naver/arcus-c-client/issues/146) PR 입니다.
io_flush() 에서 poll timeout 발생한 경우 memcached_quit_server() 호출하여 delayed reconnect 하도록 수정하였습니다.
> ENHANCE: do memcached_quit_server if poll_timeout occurs in io_flush().

- libmemcached/memcached.h
- libmemcached/version.cc
- libmemcached/version.h
**문제**
- c-client 링크하여 컴파일할 때 include directory 에 있는 server_instance.h 를 못 찾는 문제.
error: arcus/include/libmemcached/server_instance.h: No such file or directory
- 아래 PR 대로 libmemcached/include.am 에 nobase_include_HEADERS에 server_instance.h 추가 필요. (nobase_include_HEADERS 에 명시한 파일들은 ${prefix}/include 에 생성됨.)
https://github.com/naver/arcus-c-client/pull/38/commits/dffd4fa3191a41b255e72dcacf9195d545c2ad90 
=> test 시에 실수가 있어서 위 PR이 필요한 이유를 발견하지 못햇엇습니다.
**해결**
- server_instance.h 에 정의된 typedef 를 사용하지 않아 include.am 수정하지 않는 방향으로 수정하였습니다. 
- typedef 참고
```
//types.h
typedef struct memcached_server_st memcached_server_st;
//server_instance.h 
typedef struct memcached_server_st * memcached_server_write_instance_st;
```
- 향후에 위 typedef 를 types.h 에 정의하고 server_instance.h 을 제거하는 편이 좋겠습니다.
- 최신 코드도 위와 …
> FIX: don't use typedef defined in server_instance.h to not link it.

- docs/07-btree-API.md
- docs/08-attribute-API.md
링크가 잘못된 문서 주소를 참조하고 있어 수정합니다.
볼드 효과가 적용되지 않고 있어 제거했습니다.
> DOC: fix dead link

- libmemcached/fetch.cc
*error == MEMCACHED_SUCCESS 인 경우 바로 return 하기 때문에 아래 if 문에서 확인할 필요 없어 보입니다.
참고로, 최신 libmemcached 코드는 기존과 같은 형태로 같은 문제를 갖고 있긴 합니다.
> CLEANUP: removed unreachable code.

- README.md
README.md 에 compile option 이 gcc5 에서 수행되지 않아 수정하였습니다.
gcc4 버전까지는 기존과 같이 컴파일하여도 수행되었지만 아래와 같이 gcc5 에서 수행해본 결과 library 를 찾지 못합니다. 
```
[suhwan@jam2in-t003:arcus|suhwan/develop $]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes …
```
> FIX: amended compile option.

- libmemcached/get.cc
**캐시 서버가 mget, mgets 를 지원하는 경우에도 get, gets 를 사용하는 버그** ( issue : https://github.com/naver/arcus-c-client/issues/158)
memcached_connect() 호출 이후 mget 지원 여부 확인하도록 수정하였습니다.
> FIX: check enable_mget after connecting server.

- libmemcached/collection.cc
**mop get 에서 space_separated_keys 지원 여부 확인 로직 수정** : https://github.com/naver/arcus-c-client/issues/160
아직 캐시 서버와 연결되지 않은 상태에서 mop get 명령 요청 처리 시 서버 버전이 등록되있지 않아 실제로 서버가 space_separated_keys 를 지원하는 경우에도 comma_separated_keys 사용할 수 있는 문제를 수정했습니다.
- space_separated_keys_is_supported() 함수 안에서 memcached_connect() 를 호출하여 서버 버전 등록하도록 처리하였습니다.
- 이미 connected 상태이면 memcached_connect() 는 즉각 MEMCACHED_SUCCESS 를 return 합니다.
```
memcached_return_t memcached_connect(memcached_server_write_instance_st server)
{
if (server->fd != INVALID_SOCKET)
{
return MEMCACHED_SUCCESS;
}
LIBMEMCACHED_MEMCACHED_CONNECT_START();
bool in_timeout= false;
memcached_return_t rc;
if (memcached_failed(rc= backoff_handling(server, in_timeout)))
{
set_last_disconnected_host(server);
return rc;
}
...
}
```
- …
> FIX: called memcached_connect() to check space_separated_keys support in do_coll_get().

- libmemcached/error.cc
issue : program core because of server close connection https://github.com/naver/arcus-c-client/issues/164
MEMCACHED_ERRNO 가 발생할 수 있는 곳에서는 이를 검사하여 memcached_set_error() 호출하도록 수정했습니다.
> FIX: if MEMCACHED_ERRNO entered in memcached_set_error(), return instead of assert.

- libmemcached/fetch.cc
memcached_coll_fetch_result()에서 SWITCHOVER or REPL_SLAVE 응답을 받은 경우에도 NOTFOUND 로 리턴하는 문제가 있습니다.
아래 코드는 coll get 명령을 수행하는 함수에서 response 처리 부분이며 with delete 옵션을 준 경우 해당 응답을 받을 수 있습니다.
```
do_coll_get() :
#ifdef ENABLE_REPLICATION
do_action:
#endif
rc= memcached_vdo(instance, vector, veclen, to_write);
if (rc == MEMCACHED_SUCCESS)
{
if (to_write == false)
{
rc= MEMCACHED_BUFFERED;
}
else if (ptr->flags.no_reply || ptr->flags.piped)
{
rc= MEMCACHED_SUCCESS;
}
else
{
/* Fetch results */
result = memcached_coll_fetch_result(ptr, result, &rc);
#ifdef ENABLE_REPLICATION
if (rc == MEMCACHED_SWITCHOVER or rc == MEMCACHED_REPL_SLAVE)
{
ZOO_LOG_INFO(("Switchover: hostname=%s port=%d error=%s",
instance->hostname, instance->port, memcached_strerror(ptr, rc)));
memcached_rgroup_switchover(ptr, …
```
> FIX: return switchover error code when coll get with delete.

- libmemcached/arcus.cc
memcached_server_count(master) 가 리턴하는 값은 서버 개수가 아닌 그룹 개수입니다.
기존 이중화 의존성 코드로 인해 실제 서버 개수보다 부족하게 메모리를 할당한 후에 for 문에서 할당하지 않은 영역까지 접근하는 문제가 있습니다.
> FIX: allocate N replicas size in do_update_serverlist_with_master().

- libmemcached/response.cc
exist pipe 연산에서 failure 시에 MEMCACHED_SOME_EXIST 설정이 필요하여 추가하였습니다.
이에 해당하는 예시를 보이겠습니다.
```
sop exist s0 3 pipe
qwe
sop exist s0 3
qwer
RESPONSE 2
EXIST
CLIENT_ERROR bad data chunk
PIPE_ERROR bad error
```
마지막 exist 연산은 value 입력을 value length 보다 길게 입력하여 CLIENT_ERROR 를 발생시켰습니다.
첫번째 연산은 EXIST 이므로 c-client 는 이 경우에 ALL_FAILURE가 아닌 SOME_EXIST 로 설정해야 합니다.
> FIX: wrong aggregate pipe return code in case of failure.

- libmemcached/response.cc
인자 buffer 가 spacebar 부터 가리키는데, switchover_peer string 에 포함하는 문제를 수정하였습니다.
> FIX: exclude from switchover_peer string to spacebar.

- libmemcached/collection.cc
- libmemcached/response.cc
- libmemcached/response.h
collection pipe 연산 코드를 리팩토링하였습니다.
- switchover or repl_slave 응답 시에 retry 하는 로직의 복잡성을 줄이기 위하여 collection.cc 에서 연산을 모두 보낸 후에 전체 response 에 대해 aggregation 을 수행하도록 수정하였습니다.
> CLEANUP: refactored collection pipe code.

- docs/07-btree-API.md
이미 콜렉션 아이템이 존재하는 경우에 rc 값은 MEMCACHED_EXISTS 이므로 수정하였습니다.
다른 콜렉션 타입에서의 create 연산 예제 코드는 이상 없습니다.
> DOC: amended btree document.

- libmemcached/collection.cc
- libmemcached/fetch.cc
last response code 설정 검토 : https://github.com/naver/arcus-c-client/issues/179
rc 값으로 최종 상태를 알 수 없는 경우에 한하여 last response code를 설정하도록 수정하였습니다.
> CLEANUP: set last_response_code only where needed.

- tests/include.am
기존 Mac OS에서 빌드 불가능한 문제를 개선했습니다. 리눅스에서 빌드 문제 없는 점 확인했습니다.
> FIX: Fix bug that can not build on mac os. #185

- libmemcached/error.cc
> CLEANUP: Fix warning -Wformat and -Wliteral-suffix #190

- tests/mem_udp.cc
> CLEANUP: Fix warning -Wnon-literal-null-conversion #190

- example/byteorder.cc
기존 2번 워닝 수정을 `libmemcached/byteorder.cc` 파일에만 적용했으나 `example/byteorder.cc` 파일에도 같은 워닝이 있다는 것을 뒤늦게 알게 되었습니다.
> CLEANUP: Fix warning -Wunused-function #190

- libmemcached/memcached.h
https://github.com/naver/arcus-c-client/issues/190#issuecomment-1016272432
- rgroup.h 파일에서 워닝이 뜨지 않는 점에서 `#include <libmemcached/rgroup.h>`가 실행되는 시점에서는 memcached_server_info 구조체 정보가 주어진 것으로 판단했습니다.
- memcached_server_info 구조체 정보가 주어져야 하는 server_list.h 파일의 `#include <libmemcached/server_list.h>` 수행을 `#include <libmemcached/rgroup.h>` 뒤로 미뤘습니다.
- 해당 조치 취하자 워닝이 뜨지 않게 되었습니다.
> CLEANUP: Fix warning -Wvisibility #190

- libmemcached/memcached.cc
- libmemcached/rgroup.cc
__server_create_with() 에서 NULL 리턴하는 지를 검사하고 사용합니다. 
NULL 리턴하는 경우는 hostname invalid 한 경우 밖에 없는데 (server allocation 은 이미 한 상태이므로) 서버에서 hostname valid 를 확인하고 znode 를 생성하기 때문에 NULL 리턴할 일은 없을 것 같아 assert 로 두어도 될 것 같긴 합니다.
> CLEANUP: check __server_create_with() return NULL.

- m4/pandora_warnings.m4
[C Client] compile 이슈 (with ZooKeeper 3.5.X library) https://github.com/jam2in/arcus-works/issues/294
variadic-macro compile warning 을 발생시킨 컴파일 옵션은 pedantic 입니다. 
pedantic 은 ISO C 표준이 아닌 기능을 사용하였을 때 warning 을 발생시킵니다.
variadic-macro 는 표준에서 extension 된 기능 중 하나로 pedantic 이 검사하는 목록을 아래 링크에서 확인할 수 있습니다.
https://gcc.gnu.org/onlinedocs/gcc-8.4.0/gcc/C-Extensions.html#C-Extensions
variadic-macro warning 은 ignore 하도록 -Wno-variadic-macros 을 추가하였습니다.
> CLEANUP: ignore variadic-macro compile warning.

- tests/mem_functions.cc
https://github.com/naver/arcus-c-client/commit/1e19cfd963b781903ca74af9c727524f2757f096#r66963822
connection_pool_test() 함수와 connection_pool2_test() 함수에서 실패하지 않도록 pool 외부에서 정한 size 대신 pool 내부에서 정해진 max size를 사용하도록 변경했습니다.
> TEST: Update test with commit 1e19cfd

- m4/pandora_vc_build.m4
- m4/pandora_warnings.m4
8번 워닝 수정했습니다. 컴파일러 옵션 -Wlogical-op을 gcc 컴파일러를 사용할 때만 적용하도록 변경했습니다.
> CLEANUP: Ignore nested-anon-types and fix unknown-warning-option #190

- libmemcached/memcached.cc
ZOO_LOG_INFO() 함수에 이미 newline이 포함되어 있습니다.
매개변수로 넘겨주는 문자열의 newline을 제거했습니다.
> CLEANUP: Remove double newline

- libmemcached/exist.cc
- memcached_exist_by_key() 함수에서 arcus_server_check_for_update() 함수를 호출하도록 변경했습니다.
- memcached_exist_by_key() 함수에서 기존에는 add operation을 이용해 key가 저장되어 있는지 여부를 확인했습니다. add operation 대신 getattr operation을 사용하도록 변경했습니다.
- memcached_exist_by_key() 함수가 기존에 ascii protocol과 binary protocol을 모두 지원해주는 함수였습니다. getattr operation으로 변경하면서 binary protocol을 사용할 때도 정상적인 동작을 지원해주기 위해 binary protocol을 사용하는 getattr operation 구현을 추가했습니다.
- https://github.com/naver/arcus-memcached/pull/626 PR과 함께 리뷰해주시기 바랍니다.
> FIX: Call arcus_server_check_for_update() in memcached_exist_by_key() #240

- libmemcached/do.cc
- memcached_do() 함수와 memcached_vdo() 함수에서 MEMCACHED_WRITE_FAILURE 상황일 때 바로 에러 코드를 반환하도록 변경했습니다.
- 한 줄에 너무 길게 표현된 곳을 단축했습니다.
> CLEANUP: Refactored memcached_do() and memcached_vdo()

- libmemcached/connect.cc
- tests/mem_functions.cc
- connect 모듈에서 poll() system call을 수행할 때 mc->connect_timeout을 timeout 매개변수로 넣어주는데, poll() 수행 전 timeout 매개변수 검사에는 mc->poll_timeout을 사용하고 있었습니다. timeout 매개변수 검사에도 mc->connect_timeout을 사용하도록 변경했습니다.
- 단위 테스트 중 timeout failure를 발생시키는 테스트 코드에서 mc->poll_timeout을 0으로 설정해 timeout을 유도하는 부분을 mc->connect_timeout 값도 0으로 설정하도록 변경했습니다.
> INTERNAL: Check mc->connect_timeout instead of mc->poll_timeout in connect_poll()

- docs/man/memcached_behavior_get.3
- docs/man/memcached_behavior_set.3
- libmemcached/collection.cc
- libmemcached/connect.cc
- libmemcached/csl/context.cc
- libmemcached/get.cc
- libmemcached/io.cc
- libmemcached/protocol/binary_handler.c
- libmemcached/protocol/protocol_handler.c
- libmemcached/strerror.cc
- libtest/killpid.cc
- libtest/server_container.cc
- tests/parser.cc
- tests/string.cc
- util/instance.cc
`occured`로 표현된 오타가 많이 있어서 `occurred`로 고쳤습니다.
> INTERNAL: Fix typo from occured to occurred

- config/autorun.sh
- config/version.pl
- jam2in/arcus-works#368
`git describe` 명령을 통해 버전 정보를 가져올 수 없는 경우,
`unknown` 버전을 사용하는 대신 스크립트 실행을 중단합니다.
> INTERNAL: Do not use UNKNOWN version

- docs/04-list-API.md
문서에 표현된 인터페이스를 실제 구현과 통일하고 whitespace를 제거합니다.
@brido4125
현재 master branch의 문서 중 lop_insert_bulk 항목에는 index의 목록을 받는 것처럼 표현되어 있지만,
실제 구현은 (java-client와 동일하게) 여러 개의 key와 하나의 index만 받고 있습니다. 참고 바랍니다.
(single-key에 대한 piped-insert의 경우에는 다수의 index를 사용)
https://github.com/naver/arcus-c-client/blob/cfe538c2294f9c600da29061429deb6693036c78/libmemcached/collection.cc#L5223-L5231
> DOC: Fix memcached_lop_piped_insert_bulk() interface

- tests/mem_functions.cc
Mac OS에서 컴파일 시 발생하는 unused variable error를 수정합니다.
- 구동환경
```
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
- 에러
```
libmemcached/csl/parser.cc:1294:9: error: variable 'config_nerrs' set but not used [-Werror,-Wunused-but-set-variable]
int yynerrs;
tests/mem_functions.cc:1809:12: error: variable 'x' set but not used [-Werror,-Wunused-but-set-variable]
uint32_t x= 0;
^
tests/mem_functions.cc:1905:12: error: variable 'x' set but not used [-Werror,-Wunused-but-set-variable]
uint32_t x= 0;
^
tests/mem_functions.cc:2477:23: error: variable 'errors' set but not used [-Werror,-Wunused-but-set-variable]
for (uint32_t x= 0, errors= 0; …
```
> CLEANUP: Removed the unused variables

- libhashkit/jenkins.cc
- libhashkit/murmur.cc
- libmemcached/io.cc
- jam2in/arcus-works#467
fallthrough 주석을 추가하여 redhat8계열에서 발생하는 compile warning 중 하나인 implicit-fallthrough 에러를 회피합니다.
> INTERNAL: Add fallthrough comments to avoid compile warning

- libmemcached/connect.cc
- libtest/socket.cc
- jam2in/arcus-works#467
redhat8계열 리눅스에서 발생하는 컴파일 경고 중 하나인 `strncpy`에 의한 string overflow 문제 해결을 위한 PR입니다.
우선 문제가 발생한 코드는 실제 서비스에서 사용되는 `unix_socket_connect` 함수와
테스트를 위한 코드인 `set_default_socket`에서 문자열 형태의 socket path를 저장하기 위한 공간 크기 문제로 인하여 발생했습니다.
- `unix_socket_connect` 함수의 경우 다른 로직의 에러 처리와 유사하게 `memcached_set_error` 함수를 활용했습니다.
- 테스트 코드에서 활용되는 `set_default_socket`의 경우 invalid 값이 들어온 경우 변수 `global_socket`을 갱신하지 못하도록 했습니다.
- 해당 코드의 경우 실제에 쓰이지는 않고, 테스트 용도에서만 사용되므로 별도의 에러 처리 로직을 추가할 필요는 없다고 생각됩니다.
- 해당 로직을 활용하는 테스트 쪽에서 유효성을 미리 갖고 가는 편이 좋을 것으로 생각됩니다.
- 테스트에서 실제 `global_socket`을 활용하는 경우는 unix 소켓을 생성하는 함수 `pre_unix_socket` 밖에 없습니다.
- 추가적으로 테스트에서 `memcached_is_valid_servername`를 통하여 소켓 주소의 validation을 검사하나 이는 tcp/udp, unix 세 통신 프로토콜을 같은 방식으로 검사하고 있어, unix의 경우 이에 맞게 변경이 필요하다고 생각됩니다.
> INTERNAL: Handle string overflow when using strncpy

- configure.ac
- m4/pandora_canonical.m4
automake 1.16.5 버전에서 발생하는 현상인 중복 `AM_INIT_AUTOMAKE` 에러를 수정합니다.
```
autoreconf: export WARNINGS=all
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:46: error: AM_INIT_AUTOMAKE expanded multiple times
/usr/local/Cellar/automake/1.16.5/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:33: the top level
/usr/local/Cellar/automake/1.16.5/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
m4/pandora_canonical.m4:33: PANDORA_CANONICAL_TARGET is expanded from...
configure.ac:46: the top level
autom4te: error: /usr/local/opt/m4/bin/m4 failed with exit status: 1
aclocal: error: /usr/local/Cellar/autoconf/2.71/bin/autom4te failed with exit status: 1
autoreconf: …
```
> INTERNAL: Remove a duplicate init macro in configure.ac

- docs/07-btree-API.md
- #269 
btree 문서 내 space 문제 및 오타를 수정합니다.
현재 문서 내에 `b+tree`에 대한 대문자 표기가 다르게 나타나는데 해당 부분도 수정할까요?
- `b+tree` : 59개
- `B+tree` : 96개
- `B+Tree` : 52개
추가적으로 아래 표현이 조금 어색하다고 생각됩니다.
```
eflag filter 조건을 만족하는 element들 중 offset 개를 skip한 후 count 개의 element를 조회하는 함수이다.
```
좋은 방식인지는 모르겠으나 우선 현재 제가 생각하는 변경안은 아래와 같습니다.
```
eflag filter 조건을 만족하는 element들 중 offset 만큼 skip한 후 count 크기의 element 개수를 조회하는 함수이다.
```
> INTERNAL: Fix typos in a btree-API document

- docs/07-btree-API.md
- libmemcached/collection.cc
- jam2in/arcus-works#472
- naver/arcus-java-client#698
c client 내의 btree 관련 문서에서 일부 오타 및 smget/mget count 관련 내용 추가,
count 0일 시에 대한 에러 로직 추가 입니다.
> INTERNAL: Add a limit of count about bop mget/smget commands

- libmemcached/behavior.cc
- jam2in/arcus-works#476
위의 올려진 이슈를 해결합니다.
추가적으로
최신 버전의 libmemcached를 확인한 결과, `get_distribution_hash` 내에 `hashkit_get_key_fuction`을 그대로 사용 중입니다.
[link](https://github.com/awesomized/libmemcached/blob/374774dffe5f1560225648d023a121cb03dd2831/src/libmemcached/behavior.cc#L573-L580)
```c
memcached_hash_t memcached_behavior_get_distribution_hash(memcached_st *shell) {
Memcached *ptr = memcached2Memcached(shell);
if (ptr) {
return (memcached_hash_t) hashkit_get_function(&ptr->hashkit);
}
return MEMCACHED_HASH_MAX;
}
```
> INTERNAL: Return a correct type when getting distibution hash type

- libmemcached/hosts.cc
해당 PR은 아래의 수정 사항을 가집니다.
- ketama_spy 방식에서 문자열 구성이 최신 버전의 spymemcached와 다른 점을 수정합니다.
`/IP:Port-[0~39 or 99]` -> `IP:Port-[0~39 or 99]` (앞의 '/' 문자 제거)
- `KETAMA`와 `KETAMA_SPY` 내에서 for문의 변수 pointer_index의 증가 범위(0~39 or 99)가 같음에도 불구하고,
`KETAMA` 방식에서 pointer_index의 시작값을 0이 아닌 1부터 시작하는 것을 수정합니다.
- 동작 방식에는 문제 없으나 코드 가독성 목적입니다.
> INTERNAL: Fix the string handling for ketama distribution

- libmemcached/constants.h
- libmemcached/hosts.cc
- jam2in/arcus-works#485
Ketama Distribution Hash 방식에서 weighted 플래그 상관없이
기본 노드 포인트 수(`MEMCACHED_POINTS_PER_SERVER`)가 160개가 되도록 변경합니다.
(`MEMCACHED_POINTS_PER_SERVER_KETAMA`는 제거했습니다.)
> INTERNAL: Process a ketama weighted flag internally

- libmemcached/arcus.cc
- libmemcached/auto.cc
- libmemcached/collection.cc
- libmemcached/collection.h
- libmemcached/connect.cc
- libmemcached/constants.h
- libmemcached/do.hpp
- libmemcached/get.cc
- libmemcached/hash.cc
- libmemcached/hosts.cc
- libmemcached/io.cc
- libmemcached/memcached.h
- libmemcached/memcached.hpp
- libmemcached/protocol_handler.h
- libmemcached/quit.cc
- libmemcached/result.cc
- libmemcached/rgroup.cc
- libmemcached/server.cc
- libmemcached/server.h
- libmemcached/server.hpp
- libmemcached/string.cc
- libmemcached/string.h
[libmemcached](https://github.com/naver/arcus-c-client/tree/develop/libmemcached) 폴더 내의 소스파일에 있는 오탈자를 수정합니다.
> INTERNAL: Fix typos from source files in libmemcached folder

- configure.ac
`./configure` 을 성공적으로 수행할 경우 아래와 같은 메시지가 출력됩니다.
```
Configuration summary for libmemcached version 1.13.2_52
* Installation prefix:       /usr/local
* System type:               apple-darwin22.6.0
* Host CPU:                  x86_64
* C Compiler:                Apple clang version 15.0.0 (clang-1500.0.40.1)
* Assertions enabled:        yes
* Debug enabled:             no
* Warnings as failure:       yes
```
해당 버전(1.13.2)은 libmemcached 가 아니며, 컴파일 또한 arcus-c-client에 대한 것이므로 이를 수정합니다.
```
Configuration summary for arcus-c-client version 1.13.2_52
* Installation prefix:       /usr/local
* System type:               apple-darwin22.6.0
* Host CPU:                  x86_64
* C Compiler:                Apple clang version 15.0.0 (clang-1500.0.40.1)
* Assertions enabled:        yes
* Debug enabled: …
```
> INTERNAL: Print 'arcus-c-client', not 'libmemcached' when compiling

- libmemcached/hosts.cc
- #275
```
libmemcached/hosts.cc: In function 'memcached_return_t update_continuum_based_on_rgroups(memcached_st*)':
libmemcached/hosts.cc:529:65: error: 'MEMCACHED_POINTS_PER_SERVER_KETAMA' was not declared in this scope
pointer_per_server= (uint32_t) ((floor((float) (pct * MEMCACHED_POINTS_PER_SERVER_KETAMA / 4 * (float)live_servers + 0.0000000001))) * 4);
^
make[1]: *** [libmemcached/libmemcached_libmemcached_la-hosts.lo] 오류 1
make[1]: Leaving directory `/home/test/arcus-c-client-version/develop'
make: *** [all] 오류 2
```
현재 `--enable-zk-integration` 플래그 설정 시 make 실패합니다.
> FIX: Do not use MEMCACHED_POINTS_PER_SERVER_KETAMA

- config/version.pl
- #258 
git describe 실패 시 write_file 후 종료합니다.(서버와 비슷한 형태)
- develop version에서 `_` 대신 `-`를 사용합니다.
> INTERNAL: Use `-` instead of `_` in develop version

- arcus/multi_process.c
- libmemcached/arcus.cc
- libmemcached/arcus_priv.h
-  jam2in/arcus-works#467
- #281 
`with-zk-integration` 옵션을 넣고 compile 시, redhat8 계열에서 일어나는 컴파일 에러 수정입니다.
```
arcus/multi_process.c:105:7: error: ‘memset’ used with length equal to number of elements without multiplication by element size [-Werror=memset-elt-size]
memset(errors, 0, NUM_OF_PIPED_ITEMS);
^~~~~~
libmemcached/arcus.cc:941:10: error: ‘char* strncpy(char*, const char*, size_t)’ specified bound 10240 equals destination size [-Werror=stringop-truncation]
strncpy(buffer, serverlist, ARCUS_MAX_PROXY_FILE_LENGTH);
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libmemcached/arcus.cc:584:32: error: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size between 232 and 237 [-Werror=format-truncation=]
snprintf(path, sizeof(path), …
```
> INTERNAL: Fix compile errors with zookeeper in redhat8

- Makefile.am
`README.FIRST`와 `README.win32`는 libmemcached-0.53에는 있었지만 arcus-c-client에서는 존재하지 않는 파일입니다.
(initial commit d148fa3 에서 제거되었습니다.)
따라서 `EXTRA_DIST`에서 두 파일을 제거합니다.
> CLEANUP: Remove non-existent files from EXTRA_DIST

- libmemcached/connect.cc
- 에러 코드 `MEMCACHED_VERSION_FAILURE`를 추가했습니다.
- memcached_connect() 함수 내에서 memcached_version_instance() 함수가 실패했을 때 memcached_set_error() 함수를 호출하면서 MEMCACHED_VERSION_FAILURE를 사용합니다.
- 에러 코드를 추가한 의도는 connection이 수립 되기 전에 발생한 에러와 connection이 수립 되었으나 version을 가져오는데 실패한 경우의 에러를 분리하기 위함입니다.
- 이러한 분리를 통해 memcached_connect() 함수에서 connection 실패 시에 발생하는 에러 코드와 memcached_version_instance() 실패 시에 발생하는 에러 코드가 중복되어도 어느 쪽에서 문제가 생긴 것인지 알 수 있습니다.
> INTERNAL: Call memcached_set_error() when version operation is failed on connect.

- docs/02-arcus-c-client.md
- 예시 문서를 copy & paste 했을 때 발생하는 컴파일 에러를 수정합니다.
```
main.c: In function ‘main’:
main.c:25:20: error: ‘mc’ undeclared (first use in this function)
memcached_free(mc);
^
main.c:25:20: note: each undeclared identifier is reported only once for each function it appears in
```
> DOC: Fix typo in Multi-Threaded Example

- docs/02-arcus-c-client.md
- docs/04-list-API.md
- docs/05-set-API.md
- docs/06-map-API.md
- docs/07-btree-API.md
- docs/08-attribute-API.md
- docs/arcus-c-client-user-guide.md
- DOCS 내 오탈자를 제거합니다.
- 일부 API와 DOCS와 변수명이 다른 것에 대해서는 유지했습니다.
- ex) response → result
- 추후에 코드 변수명을 변경할 지 Docs를 수정할 지는 고려해야 할 것 같습니다.
> DOC: Correct typos

- docs/06-map-API.md
- libmemcached/collection.cc
- libmemcached/collection.h
- tests/mem_functions.cc
- jam2in/arcus-works#579
- mop upsert 명령어 수행 인터페이스를 추가합니다.
- mop upsert 관련 테스트를 추가합니다.
> arcus-memcached에서 mop upsert 명령어가 들어간 버전이 릴리즈될 때까지 draft
> FEATURE: Add a mop upsert command

- .gitignore
- devtools/maketags.sh 파일은 커밋 이력으로 보아 필요한 파일로 추정되지만 gitignore에서는 devtools 내의 모든 파일을 무시하도록 되어 있다.
- gitignore에서 devtools/maketags.sh 파일을 무시하지 않도록 합니다.
> INTERNAL: Make `devtools/maketags.sh` not ignorable by git.

- tests/include.am
- 현재 Make install 시 tests/storage.h가 포함됩니다.
- `noinst_HEADERS`에 지정되지 않는 경우 make dist를 통한 tar.gz 생성 시 해당 헤더 파일이 포함되지 않아 추가했습니다.
> FIX: Exclude tests/storage.h during installation

- tests/storage.cc
- https://github.com/jam2in/arcus-works/issues/589
- mset 테스트 코드를 각 단계별 함수로 분리합니다.
- req 객체 생성
- API 호출 결과 `memcached_return_t` 값 검증
- get 함수로 서버에 저장한 값 검증 
- 추후에 추가할 madd, mreplace 등의 테스트 코드에서 각 함수를 호출할 예정입니다.
> TEST: Split each step of the mset test code into functions.

- libmemcached/auto.cc
- libmemcached/storage.cc
- https://github.com/jam2in/arcus-works/issues/602
- snprintf()로 정수형 변수 출력 시 Whitespace가 포함되어도 버퍼 크기 산정에서 이를 고려하지 않는 점을 수정합니다.
> FIX: Fix buffer size when calling snprintf() with leading whitespace and integer value.

- libmemcached/connect.cc
- libmemcached/io.cc
- libmemcached/memcached.h
- 
- `TARGET_OS_LINUX`는 configure 과정에서 정의하는 변수입니다.
- `__linux__`는 Linux 머신에 설치된 GCC가 정의하는 변수이고, 이를 사용하는 것이 더 일반적입니다.
- https://stackoverflow.com/a/4605893
- https://github.com/cpredef/predef/blob/374dfcc5581db7c968e794f05129a996acd033b2/OperatingSystems.md#linux-kernel
> FIX: Use `__linux__` instead of `TARGET_OS_LINUX` to check if the current OS is Linux.

- libmemcached/arcus.cc
- jam2in/arcus-perl-client#66
- proxy_lock 파일명에 sequential index를 추가합니다.
- 하나의 프로세스에서 다수의 proxy를 생성하는 경우의 이름 충돌을 방지합니다.
> FIX: Add proxy_lock_count for multiple proxy in a process

- docs/03-key-value-API.md
- jam2in/arcus-works#607
- 문서 내 delete API의 잘못된 내용을 수정합니다.
- 추후에는 expiration을 가변 인자로 변경하는 것도 고려해볼 수 있을 것 같습니다.
> DOC: Fix an incorrect description of expiration in the delete API

- configure.ac
- naver/arcus-memcached#699
- system path보다 prefix 경로에 설치된 의존성을 우선 탐색하도록 합니다.
> FIX: Check dependencies in the prefix path before the default path

- docs/01-arcus-cloud-basics.md
- #312
- ~arcus-cloud-basic 문서에 flags 설명을 추가하는 과정에서 누락되었습니다.~
- ~머리말의 목차에 링크를 추가합니다.~
- flags 관련 설명을 수정합니다.
> DOC: Modify a description about the flags

- docs/05-set-API.md
- #320
- set 아이템 관련 API 문서를 list와 유사한 형식으로 변경했습니다.
- 다음 PR에서는 Map과 Btree API 수정이 순차적으로 진행될 예정입니다.
- 작업을 따로 진행하는 이유는 각 타입마다 제공하는 API가 조금씩 다르고, 일부 내용은 아직 확인이 완료되지 않았기 때문입니다.
> DOC: Modify examples for the set document

- libmemcached/response.cc
- jam2in/arcus-works#652
- 서버로부터 받은 response 코드에서 VALUE 라인을 파싱할 때, 성공/실패 상관없이 무조건 cursor_active를 증가하도록 변경합니다.
- 서버에서 보내는 response 코드는 VALUE 라인이 응답의 마지막이 되는 경우가 없으며, END 라인을 보내어 마지막을 알려줍니다.
- `NOTFOUND` / `OUT_OF_RANGE` 가 아닌 `PROTOCOL_ERROR`, `MEMCACHED_PARTIAL_READ` 에러가 발생하는 경우, reconnect가 되어 문제는 없을 것으로 보입니다.
> INTERNAL: Increase the cursor_active even in non-successful situations

- libmemcached/collection.cc
- libmemcached/collection.h
- libmemcached/types.h
- #327
- update_filter를 deprecated 시키고, eflag_update로 변경합니다.
> INTERNAL: Rename update_filter to eflag_update

- libmemcached/collection.cc
- #328
- 누락된 update_filter 이름을 eflag_update로 변경합니다.
> INTERNAL: Rename the missing update_filter to eflag_update

- libmemcached/collection.cc
- https://github.com/jam2in/arcus-works/issues/661#event-15701315090
- query_init에서 bkey validation check 하도록 변경합니다.
> INTERNAL: Validation check for the bkey

- libmemcached/collection.cc
- jam2in/arcus-works#655
- bkey string을 생성하는 공통된 로직을 하나의 함수로 넣어 처리합니다.
- Invalid query type의 경우, -1을 리턴합니다.
> INTERNAL: add a function to generate a bkey string

- libmemcached/collection.cc
- tests/mem_functions.cc
- #321
- #181 
- exist API에서 MEMCACHED_NOT_EXIST를 성공적인 경우로 변경합니다.
- 사용자는 memcached_get_last_response_code API를 통해 존재 여부를 확인할 수 있습니다.
> INTERNAL: Add a success case for 'NOT_EXIST' in the exist API

- libmemcached/collection.cc
- #329
- uninitialize 컴파일 에러를 해결합니다.
- rc 값을 MEMCACHED_SUCCESS로 초기화합니다.
- number_of_piped_items 가 0보다 작거나 같은 경우, MEMCACHED_INVALID_ARGUMENTS를 반환합니다.
> FIX: Initialization of the rc value in pipe operations

- docs/07-btree-API.md
- btree 아이템 관련 API 문서를 map, set과 유사한 형식으로 변경했습니다.
> DOC: Modify examples for the btree document

- libmemcached/get.cc
- jam2in/arcus-works#675
- mget/mgets 지원 여부를 확인하는 서버 버전 검사 로직에서 불필요한 부분을 제거합니다.
> INTERNAL: Remove unnecessary lines in the version check of get API

- .gitignore
- devtools/clean-whitespace.pl
- Arcus-C-Client의 파일에서 whitespace를 제거하는 Perl 스크립트를 추가합니다.
- whitespace를 제거하는 방식은 서버의 clean-whitespace와 동일합니다.
- Git에서 관리하는 파일들에서 whitespace를 제거하도록 했습니다.
- png(이미지)파일은 제외하도록 했습니다. 
- 이후 whitespace가 제거된 파일을 PR로 올릴 예정입니다.
> INTERNAL: Add a clean-whitespace script file

- README.md
- #342
- README에서 줄바꿈 요소로 줄 마지막에 띄어쓰기 2개를 넣어 활용하고 있습니다.
- 하지만 VS code에서 white space 제거 기능을 키고, README를 수정할 경우 해당 문자(띄어쓰기 2개)까지 제거가 되어 버립니다.
- 줄을 바꿀 때, 띄어쓰기 2개 대신에 HTML 문법인 `<br>`을 활용합니다.
> DOC: Use HTML line break element

- devtools/clean-whitespace.pl
- #342
- autotools에서 configure와 Makefile 생성에 사용되는 am과 ac 파일은 tab 문자열을 변경하지 않습니다.
- Makefile 에서는 space가 아닌 탭 문자로 사용하도록 되어 있습니다.
> INTERNAL: Don't change a tab character in .ac/am files

- README.md
- #343
- HTML 줄바꿈 대신에 Markdown의 리스트를 활용합니다.
```markdown
In addition to those who had contributed to the original libmemcached, the following people at NAVER have contributed to arcus-c-client.
- Hoonmin Kim (harebox) [hoonmin.kim@navercorp.com](mailto:hoonmin.kim@navercorp.com); [harebox@gmail.com](mailto:harebox@gmail.com)
- YeaSol Kim (ngleader) [sol.k@navercorp.com](mailto:sol.k@navercorp.com); [ngleader@gmail.com](mailto:ngleader@gmail.com)
- HyongYoub Kim [hyongyoub.kim@navercorp.com](mailto:hyongyoub.kim@navercorp.com)
```
> DOC: Use a list instead of line breaks

- libmemcached/csl/common.h
- libmemcached/csl/context.cc
- libmemcached/csl/context.h
- libmemcached/csl/parser.yy
- libmemcached/csl/scanner.l
- libmemcached/csl/server.h
- libmemcached/csl/symbol.h
- #344
- csl 폴더 내 파일들의 whitespace를 제거합니다.
> INTERNAL: Remove whitespace in csl files

- devtools/clean-whitespace.pl
- #344
- whitespace 제거 스크립트에서 m4 파일을 제외합니다.
> INTERNAL: Exclude m4 files from clean-whitespace

- docs/02-arcus-c-client.md
- 잘못 표기된 default timeout 값을 수정합니다.
- `MEMCACHED_DEFAULT_TIMEOUT` 값은 1.7.3 버전부터 700ms였습니다.
- https://github.com/naver/arcus-c-client/commit/6fb2fa50890c3320d9566a9ed24d89f2b1ff4d2c 에서 변경할 때 문서는 함께 수정하지 않아 잘못된 값이 지금까지 남아있었습니다.
> DOC: Fix `MEMCACHED_DEFAULT_TIMEOUT` value

- libmemcached/response.cc
-  #337
- fetch 연산에서 키가 MEMCACHED_MAX_KEY보다 클 경우, 덮어쓰기가 발생하지 않도록 방지합니다. 만약 덮어쓰기가 발생하면 이를 로그에 기록합니다.
- OVERWRITE가 발생한 경우, 사용자는 키 길이만으로 이를 충분히 감지할 수 있을 것으로 보입니다.
- Binary 프로토콜 관련 부분도 수정했습니다.
- Binary 프로토콜에서는 키 길이를 알 수 있기 때문에, MEMCACHED_MAX_KEY만큼 데이터를 저장한 후 나머지 데이터는 임시 버퍼로 flush 처리했습니다.
> INTERNAL: Fix an overwrite issue for the big key

- libmemcached/fetch.cc
- libmemcached/hash.cc
- #339
- 내부 로직에서 MEMCACHED_MAX_KEY 사용에 일관되지 않은 부분을 수정합니다.
- 확인해본 결과, 두 부분 외에는 문제가 없는 것으로 확인됩니다.
> INTERNAL: Fix the inconsistent MEMCACHED_MAX_KEY usage

- libmemcached/fetch.cc
- #334
- memcached_fetch 함수가 리팩토링되었습니다.
- use_udp 부분을 확인한 결과, 필요하지 않아서 제거했습니다.
- `if (result_buffer == NULL || memcached_failed(*error))` 조건문에서 `memcached_failed`를 제거했습니다.
- memcached_fetch_result에서 error 값이 memcached_success가 아닌 경우, 항상 NULL을 반환하도록 되어 있습니다.
- libmemcached를 확인한 결과, 별다른 변경 사항은 없는 것으로 보입니다.
- [libmemcached/src/libmemcached/fetch.cc](https://github.com/awesomized/libmemcached/blob/b32a7148f30b60020a28d68e4462894af5151d3a/src/libmemcached/fetch.cc#L18-L108)
> INTERNAL: Refactor a memcached_fetch function

- libmemcached/sasl.cc
- #356 
- https://github.com/awesomized/libmemcached/commit/4952d9d842e9c13eace3a986bf748001d5d6852d
- libmemcached에서 처리한 방식과 동일하게 처리했습니다.
- reinterpret_cast 는 c++에서 제공하는 타입캐스트 연산자로 Pointer → 일반 자료형, 일반 자료형 → Pointer 형태로 형변환 시  활용됩니다.
> INTERNAL: Fix the cast-function-type error

- docs/02-arcus-c-client.md
- docs/03-key-value-API.md
- docs/04-list-API.md
- docs/05-set-API.md
- docs/06-map-API.md
- docs/07-btree-API.md
- 
- 개행을 추가하여 문서의 가독성을 높였습니다.
- 내용은 [link](https://app.gitbook.com/o/meG2sum1yom68imzYp1p/s/bg5yQEO2WA74oCe0UM0y/) 에서 미리보기가 가능합니다. (로그인 필요)
- 일부 함수의 길이가 너무 길어 줄바꿈이 어려운 경우, 그대로 두었습니다.
- ex) memcached_coll_smget_result_get_trimmed_key_length
- 이런 함수들은 추후에 함수명을 변경하거나, `typedef`를 사용하여 재정의하는 것이 좋을 것 같습니다.
> DOC: Modify documents to improve readability

- libmemcached/server_list.cc
- #368 
- [jam2in/arcus-works#717](https://github.com/naver/arcus-c-client/pull/368#issuecomment-2834149556)
- Ubuntu 24.04에서 발생하는 에러를 수정합니다.
```js
libmemcached/server_list.cc:80:32: error: pointer 'ptr' may be used after 'void* realloc(void*, size_t)' [-Werror=use-after-free]
80 |     *error= memcached_set_errno(*ptr, MEMCACHED_MEMORY_ALLOCATION_FAILURE, MEMCACHED_AT);
|             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libmemcached/server_list.cc:69:61: note: call to 'void* realloc(void*, size_t)' here
69 |   new_host_list= (memcached_server_write_instance_st)realloc(ptr, sizeof(memcached_server_st) * count);
|            
```
- __server_create_with 에서 NULL이 반환되는 경우는 invalid hostname, malloc failure로
미리 hostname validation 검사 및 realloc을 통한 공간 확보가 …
> INTERNAL: Fix a compile error in Ubuntu 24.04

- libmemcached/collection.cc
- tests/mem_functions.cc
- jam2in/arcus-works#721
- `unique` | `duplicate` 지정하지 않는 old smget 요청을 deprecated 처리합니다.
- 컴파일 타임에 경고를 보내는 것이 아니고, old smget query를 사용하여 함수를 호출하면 에러가 반환됩니다.
> FEATURE: Return `MEMCACHED_DEPRECATED` when using old query_init function in memcached_bop_smget

- libmemcached/arcus.cc
- #374 
long-running-test를 위한 빌드 중 아래와 같은 에러가 발생하였습니다.
```
libmemcached/arcus.cc: In function 'void do_arcus_zk_watcher_cachelist(zhandle_t*, int, int, const char*, void*)':
libmemcached/arcus.cc:1134:8: error: 'ZOO_CHILD_EVENT' cannot appear in a constant-expression
case ZOO_CHILD_EVENT:
^
libmemcached/arcus.cc:1137:8: error: 'ZOO_NOTWATCHING_EVENT' cannot appear in a constant-expression
case ZOO_NOTWATCHING_EVENT:
^
libmemcached/arcus.cc:1140:8: error: 'ZOO_SESSION_EVENT' cannot appear in a constant-expression
case ZOO_SESSION_EVENT:
```
- switch의 각 case에는 상수만 위치할 수 있는데, ZOO_XXX_EVENT가 변수라서 문제가 생기는 것 같습니다.
```c
#define CREATED_EVENT_DEF 1
#define DELETED_EVENT_DEF 2
#define CHANGED_EVENT_DEF 3
#define CHILD_EVENT_DEF 4
#define SESSION_EVENT_DEF -1
#define NOTWATCHING_EVENT_DEF -2
const …
```
> CLEANUP: Fix compile error in switch-case

- ChangeLog
- config/version.pl
> version 1.14.1
