- libmemcached/collection.cc
- libmemcached/collection.h
- libmemcached/fetch.cc
- libmemcached/response.cc
Refer to issue number 6 - https://github.com/naver/arcus-c-client/issues/6.
> [JOON_SMGET_ERROR_HANDLING] make correction in smget error handling.

- libmemcached/collection.cc
- libmemcached/collection.h
- libmemcached/fetch.cc
- libmemcached/response.cc
JOON_SMGET_ERROR_HANDLING code tag를 제거하였습니다.
> [JOON_SMGET_ERROR_HANDLING] remove code tag.

- .gitignore
git ignore list 에 필요한 항목을 추가하였습니다.
> add gitignore lists

- tests/mem_functions.cc
OS X의 unnamed semaphore 미지원으로, named semaphore 를 사용하도록 수정하였습니다.
> fix for semaphore on os x

- docs/06-btree-API.md
@jhpark816 
btree doc 문서에서,
memcached_bop_piped_insert_bulk(),
memcached_bop_ext_piped_insert_bulk()의 arguments,
그에 대한 설명이 잘못 되어 있던 부분을 수정 했습니다.
B+tree element 일괄 삽입 예제가 빠져 있던 부분을 추가 했습니다.
확인 요청 드립니다.
> CLEANUP: edit btree collection doc incorrect description

- clients/memcapable.cc
- docs/07-btree-API.md
pacages -> packages
bkery -> bkey
interger -> integer
qeury -> query
> Typo Fixed

- libmemcached/arcus.cc
Issue : replication cluster인 경우, ZK에 client info를 등록되지 않는 문제가 있다.
ZK에 client info 등록 시 "arcus" znode 에만 등록하기 때문에 문제가 있었습니다.
"arcus_repl" znode 에도 등록하도록 추가하였습니다.
> FIX: Register client info in replication znode

- libmemcached/arcus.cc
arcus cluster type을 확인한다.
ENABLE_REPLICATION이면 먼저 "/arcus_repl/cache_list/{svc_code}" znode 확인하고
존재하지 않는 경우 "/arcus/cache_list/{svc_code}" znode 확인한다.
"/arcus/cache_list/{svc_code}" znode도 존재하지 않는 경우
단순 리턴으로 timeout 발생시켜 응용을 중지시킨다.
Reviewer
> FEATURE: Change the check method of arcus cluster type

- libmemcached/util/pool.cc
memcached pool 관련 리팩토링을 위한 PR 입니다.
1. pool array의 최 상단 위치를 의미하는 firstfree 변수의 이름을 top으로 변경했습니다.
2. pool이 NULL일 때 pool size "1"을 리턴하던 기존 코드에서 "0"을 리턴하도록 변경 했습니다.
reviewer
확인 요청 드립니다.
> CLEANUP: changed the name of top pointer of free mc pool and defined the size of a pool that is null to 0.

- libmemcached/arcus.cc
- libmemcached/constants.h
- libmemcached/memcached.cc
- libmemcached/memcached.h
- libmemcached/util/pool.cc
serverlist / grouplist를 기반으로 serverinfo를 생성해 반영하는 설계 PR 입니다.
> ENHANCE: update mc fetched from pool based on ketama_version of master

- libmemcached/allocators.cc
develop으로 고쳐서 다시 PR 합니다.
[이전 PR 링크](https://github.com/naver/arcus-c-client/pull/61 )
> FIX: fix nullpointer dereferencing

- util/instance.cc
codacy 정적 검사 결과 초기화 하지 않은 변수에 더하는 코드가 있어 수정했습니다.
> FIX: Uninitialized variable: total_read

- libmemcached/arcus.cc
#70 관련 PR입니다.
zookeeper와 처음 연결하기 위한 2가지 함수 `arcus_proxy_create(), do_arcus_connect()`에서
연결이 완료되기를 wait하는 코드가 중복되어 있어 연결과 wait를 `do_arcus_zk_connect()` 한곳에서
처리하도록 변경 했습니다.
참고로, `arcus_proxy_create()`의 wait 코드는 문제가 있었던 상태라서 같이 수정 했습니다.
- wait 로직은 `arcus->is_initializing` 변수를 기반으로 wait 하는 로직입니다.
- `arcus_proxy_create()`에서는 lock_arcus mutex lock을 잡지 않고 확인하여 wait하고 있었는데
- `arcus->is_initializing=false`로 설정하는 부분은 lock_arcus mutex lock을 잡고 설정하도록 되어있습니다.
do_arcus_zk_connect()를 호출하는 로직은 세군데 이고 모두 문제 없이 동작 합니다.
- arcus_proxy_create()
- 처음 연결로 wait code가 do_arcus_zk_connect() 내부로 포함
- do_arcus_connect()
- 처음 연결로 wait code가 do_arcus_zk_connect() 내부로 포함
- zk_global_watcher
- zk session을 관리하는 watcher 로직으로, SESSION_EXPIRED에 의해 reconnect
- arcus->is_initilizing = false 인 상태로 wait 하는 code가 수행되지 않음이 보장
- …
> CLEANUP: remove duplicate code waiting for zk connect

- libmemcached/arcus.cc
#74 관련 PR 입니다.
초기화가 필요한 상태에서만 client_info znode create와
cache_list znode watcher 등록 하도록 수정 했습니다.
초기화 필요 상태는 `arcus->zk.is_initializing == true` 조건을 이용했고
client_info znode create, cache_list znode watcher 등록을 위해
lock_arcus를 잡지 않고 `process_initializing`를 이용하도록 했습니다.
client_info는 항상 현재 session이 생성한 znode만 존재할 수 있도록
이미 있으면 제거하고 다시 생성하도록 zoo_multi()를 사용하여 replace 합니다.
@jhpark816 
확인 요청 드립니다.
> FIX: client_info and watcher registration only in invalid session

- libmemcached/auto.cc
- libmemcached/delete.cc
- libmemcached/exist.cc
- libmemcached/flush.cc
issue : https://github.com/jam2in/arcus-memcached-EE/issues/776 관련 PR 입니다.
key test 가 빠져 있는 곳에 추가하였습니다.
> FIX: added key test where it needs to be tested.

- libmemcached/response.cc
MEMCACHED_PARTIAL_READ와 관련된 부분들 리팩토링 하였습니다.
@jhpark816 리뷰 요청드립니다.
> CLEANUP: refactoring MEMCACHED_PARTIAL_READ part.

- libmemcached/response.cc
textual_coll_piped_response_fetch()에서의 재귀 구조를 제거하기 위해 새로운 함수 get_status_of_coll_pipe_response() 추가
- 기존 코드에서 memcached_coll_response()를 재귀 호출 하던 부분을, get_status_of_coll_pipe_response()를 호출하도록 수정.
- 기존 코드의 구조
- 파이프 연산의 결과를 읽기 위해 다음과 같은 순서로 함수를 호출.
- memcached_coll_response()
- 버퍼에 남아 있는 old command 제거 
- memcached_read_one_coll_response()
- memcached_server_response_decrement() 호출
- textual_read_one_coll_response()
- response를 파싱해 return code 획득.
- 파이프 연산의 결론(END, PIPE_ERROR)을 알기 위해 한번 더 파싱 과정 수행
- get_status_of_coll_pipe_response()는 기존의 코드가 수행하던 로직을 모두 수행함
- 버퍼에 남아 있는 old command 제거
- memcached_server_response_decrement() 호출
- response를 파싱해 return code 획득
- textual_read_one_coll_response의 파싱 코드를 바탕으로, 파이프 연산의 결과로 나오지 않는 response를 파싱하는 코드를 제거
- 제거된 응답은 다음과 같음 
- "ATTR..."
- "VALUE..."
- …
> CLEANUP: remove recursion of textual_coll_piped_response_fetch

- libmemcached/response.cc
SERVER_ERROR처럼 ERROR, CLIENT_ERROR의 상세 에러 메세지를 memcached_server_st의 error_messages field에 저장하도록 하였습니다.
참고로, 최신 libmemecached 는 CLIENT_ERROR, SERVER_ERROR의 상세 에러 메세지를 위 PR처럼 저장해두고 있습니다.
> FEATURE: stored detail error message of response in error_messages field

- libmemcached/server.cc
- libmemcached/server.h
- libmemcached/util/version.cc
서버 버전 체크하는 조건이 잘못 되어있어서 수정하였습니다.
> FIX: fixed version check condition

- docs/02-arcus-c-client.md
#93 에서 추가된 error message API의 사용법 문서 추가를 위한 PR 입니다.
아래 두 API 사용을 노출했고, detail error message API 사용을 권장 합니다.
- `const char *memcached_last_error_message(memcached_st *mc)`
- `const char *memcached_detail_error_message(memcached_st *mc, memcached_return_t rc)`
@SuhwanJang @jhpark816 
리뷰 요청 드립니다.
> DOC: add error message API usage

- tests/mem_functions.cc
이슈 #89 관련 PR입니다.
파이프 연산 도중 too large value를 삽입해 PIPE_ERROR bad error를 유도합니다.
> TEST: add test case for PIPE_ERROR bad error

- docs/01-arcus-cloud-basics.md
- docs/02-arcus-c-client.md
- docs/03-key-value-API.md
- docs/07-btree-API.md
- docs/08-attribute-API.md
- docs/09-other-API.md
- docs/arcus-c-client-user-guide.md
코드나 로그에 관한 부분을 제외하고 Arcus로 표기된 부분을 ARCUS로 바꾸었습니다.
> Capitalize ARCUS

- docs/04-list-API.md
- docs/05-set-API.md
- docs/07-btree-API.md
c 클라이언트에 list item indentation이 된 부분이 있어 수정하였습니다
> DOC: fix list indentation

- libmemcached/arcus.cc
gethostbyname() 가 실패한 경우 host 는 NULL 이 되어 inet_ntoa(*((struct in_addr *)host->h_addr)) 에서 NPE 가 발생할 수 있는 문제가 있습니다.
> FIX: registered "NULL" if hostname lookup fails in do_add_client_info().

- libmemcached/auto.cc
auto.cc 에 text_incr_decr() 함수를 리팩토링하였습니다.
- more readable
- key string을 copy할 필요 없이 바로 io 할 수 있음.
> CLEANUP: refactored text_incr_decr() in auto.cc

- libmemcached/delete.cc
delete.cc 에 ascii_delete() 함수를 리팩토링하였습니다.
- more readable
- key string을 copy할 필요 없이 바로 io 할 수 있음.
> CLEANUP: refactored ascii_delete() in delete.cc

- libmemcached/io.cc
memcached_io_read() 에서 recv() 수행 부분을 별도 함수 (static _io_fill()) 로 분리하였습니다.
> CLEANUP: separated the _io_fill() for receiving data from memcached_io_read()

- libmemcached/get.cc
forward declare static functions
참고로 간단한 수정이긴 하지만 코드 태그 없으면 diff 확인이 어려워서 넣었습니다.
> CLEANUP: forward declare static functions

- libmemcached/get.cc
issue: "CLEANUP: enable optimize mget operation with instance version" 리뷰와 수정 #131 - mget optimized 사전 작업 PR
- 명령 처리 로직 관점에서 ascii protocol 의 single key get 과 multiple key get 을 분리하였습니다.
- 기존 방식 
- single get API : memcached_get() / multiple get API : memcached_mget()
- 두 API 가 내부적으로 같은 함수를 사용하여 명령 처리
- 변경 방식
- memcached_get()은 memcached_get_by_key() 호출.
=> 하나의 캐시 노드로 하나의 키만을 조회 요청하는 로직.
- memcached_mget() 은 memcached_mget_by_key() 호출.
=> 다수의 캐시 노드로 다수의 키를 조회 요청하는 로직.
- 추가될 arcus mget 은 memcached_mget_by_key() 에서 수행. vector header 생성 부분만 달라지게 됨.
- 두 연산에서 공통적으로 사용하는 before_get_query() 함수 정의
-  initialize_query() 수행, key 검사, pending response read 수행.
- 참고:
- get.cc 에서 io write 시 모두 memcached_vdo, do() 의 내부 함수를 호출하는 방식으로 되어 있네요.
- 이렇게 구현된 이유는 noreply 설정된 상태에서 get 연산 사용 가능을 염두해 둔 것 같기도 …
> CLEANUP: separated get and mget

- libmemcached/get.cc
issue: "CLEANUP: enable optimize mget operation with instance version" 리뷰와 수정 #131 - mget optimized PR
multiple get 요청에서 캐시 서버가 arcus mget 명령을 지원하는 버전인 경우 mget 명령을 사용하도록 변경하였습니다.
- arcus mget 추가된 버전 :  
- 1.11.0 commit : https://github.com/naver/arcus-memcached/commit/e75e6091f80685dc2f72711c36d29de6dbeee1b3
- 0.7.0-E commit : https://github.com/jam2in/arcus-memcached-EE/commit/1566980be366edc2eb1ee497ff9e15cfaa901ef6
> FEATURE: supported mget command, efficient for getting multiple items.

- libmemcached/collection.cc
mop get, bop mget, bop smget 에서 key list 의 구분자를 캐시 서버 버전을 확인하여 space 를 사용하도록 변경하였습니다.
> FEATURE: supported space-separated keys.

- libmemcached/collection.cc
- libmemcached/get.cc
multi key operation 에서 키 전송이 실패한 경우 해당 인스턴스로의 protocol 은 어긋난 상태이므로 
이러한 인스턴스로의 요청은 더 이상 하지 않도록 실패된 인스턴스 정보를 저장해두어 처리하였습니다.
> FIX: handled failure in the multi key operation.

- libmemcached/get.cc
**mgets 지원** ( issue : https://github.com/naver/arcus-c-client/issues/151 )
캐시 서버의 버전이 mgets 명령을 지원하고, support_cas 가 enabled 된 경우에 mgets 명령을 사용하도록 변경하였습니다.
- API 는 기존과 동일하게 memcached_mget() 를 사용하기 때문에 테스트 코드와 문서에 변경된 사항은 없습니다.
참고 - memcached_mget API https://github.com/naver/arcus-c-client/blob/master/docs/03-key-value-API.md 설명:
```
Key-value item을 조회하는 API는 두 가지가 있다.
char *
memcached_get(memcached_st *ptr,
const char *key, size_t key_length,
size_t *value_length, uint32_t *flags,
memcached_return_t *error)
주어진 key에 대한 value를 조회한다. 반환된 결과는 NULL이 아닌 경우 반드시 free 해주어야 한다.
memcached_return_t
memcached_mget(memcached_st *ptr,
const char * const *keys,  const size_t *key_length,
size_t number_of_keys)
char *
memcached_fetch(memcached_st *ptr,
char *key, size_t *key_length,
size_t …
```
> FEATURE: supported mgets command.

- configure.ac
ZK 3.5 Library 컴파일 가능하도록 THREADED 옵션 활성화하였습니다.
> FEATURE: enable zookeeper multi thread mode

- libmemcached/response.cc
issue (https://github.com/naver/arcus-c-client/issues/172) : SWITCHOVER or REPL_SLAVE 응답인 경우 switchover slave index 설정 수정
이슈에 기술된 대로 수정하였습니다.
> CLEANUP: set switchover slave index.

- arcus/multi_threaded.c
```cpp
// 자원 해제 코드
if (pool) {
arcus_pool_close(pool);
memcached_pool_destroy(pool);
}
if (global_mc) {
memcached_free(global_mc);
}
```
- `memcached` 혹은 `arcus` 요청 실패 시 자원 해제 코드 수행하는 로직 추가
- `arcus_pool_connect()` 실패 시 `memcached_pool_push()` 호출하지 않고 자원 해제 코드 수행하도록 변경
- 오류 상황에 따라 서로 다른 리턴 값을 갖도록 변경
> ENHANCE: Enhance multi_threaded.c #186

- clients/memcapable.cc
- libmemcached/byteorder.cc
- libtest/server.cc
> CLEANUP: Fix warning -Wunused-const-variable and -Wunused-function #190

- libmemcached/arcus.cc
- libmemcached/array.c
> CLEANUP: Fix warning -Wpointer-bool-conversion #190

- libmemcached/fetch.cc
> CLEANUP: Fix warning -Wmisleading-indentation #190

- tests/mem_functions.cc
> CLEANUP: Fix warning -Wformat-truncation #190

- libmemcached/behavior.cc
> CLEANUP: Fix warning -Wimplicit-fallthrough #190

- libtest/socket.cc
> CLEANUP: Fix warning -Wstringop-truncation #190

- libmemcached/arcus.cc
https://github.com/naver/arcus-c-client/issues/206#issuecomment-1005387930
위 방향으로 작업 진행 했습니다. 검토 부탁드립니다.
> FIX: Use MAP_ANONYMOUS to call function mmap() on MacOS #206

- tests/hashkit_functions.cc
https://github.com/naver/arcus-c-client/issues/200#issuecomment-1005404103
위와 같은 방향으로 작업 진행했습니다. 검토 부탁드립니다.
> CLEANUP: Fix hashkit_get_function_test() #200

- libmemcached/arcus.cc
https://github.com/jam2in/arcus-works/issues/316
arcus_proxy_connect() 함수에 매개변수의 validation 과정을 추가했습니다.
> INTERNAL: Add validation in arcus_proxy_connect()

- README.md
- docs/test_faq.md
유닛 테스트 관련 문서를 추가했습니다.
전체 테스트 방법과 개별 테스트 방법을 설명하고, 테스트 실패 케이스 1개를 소개하였습니다.
> DOC: Add unit test FAQ

- docs/04-list-API.md
- docs/05-set-API.md
- docs/06-map-API.md
- docs/07-btree-API.md
> DOC: Fix piped operation

- libmemcached/csl/parser.yy
- libmemcached/csl/scanner.l
- jam2in/arcus-works#461
아래 파일을 추가합니다. 기존 scanner(.cc, .h) 또는 parser(.cc, .h)를 재생성하지는 않았습니다.
- `libmemcached/csl/scanner.l`
- `libmemcached/csl/parser.yy`
https://github.com/awesomized/libmemcached/tree/0.53
> INTERNAL: Import scanner.l and parser.yy from libmemcached-0.53

- libmemcached/constants.h
- libmemcached/hosts.cc
- #263 
해당 PR 중 리뷰에 방해되는 whitespace를 제거합니다.
> INTERNAL: Remove white space in some source files

- libmemcached/hosts.cc
- #275
- [96f9774](https://github.com/naver/arcus-c-client/compare/edec10cb99424252a5eb1343eee6363ee0f682fa..96f9774026d98179e9b78ee89f826e4d2b5d5d2c)
update_continuum 함수에서 distribution hash 구성을 위한
2개의 for 문 (Ketama spy, Non Ketama spy)을 하나의 for 문으로 합칩니다.
> CLEANUP: Refactor for loops in update_continuum function

- ChangeLog
- config/version.pl
ChangeLog 초안입니다.
> memo: 릴리즈 시 ChangeLog 날짜 수정 필요
> version 1.13.3

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-refactoring-request.md
- .github/PULL_REQUEST_TEMPLATE.md
- naver/arcus-java-client#733
- Issue/PR template을 추가합니다.
- 템플릿 내용은 java-clinet와 동일합니다.
> DOC: Create issue/pr templates

- libmemcached/storage.cc
- https://github.com/jam2in/arcus-works/issues/589
- mset API 사전 PR로 send_xxx() 함수의 인자를 변경합니다.
> CLEANUP: Use server_key instead of group_key and group_key_length.

- ChangeLog
- config/version.pl
- version commit입니다.
- 날짜는 09월 02일(월요일) 기준
> version 1.14.0

- docs/01-arcus-cloud-basics.md
- docs/03-key-value-API.md
- jam2in/arcus-works#606
- KV 문서에 예제 코드를 추가했습니다.
- libmemcached 문서를 확인했으나 예제 코드가 따로 존재하지 않아 저희 쪽 다른 문서를 참고했습니다.
> DOC: Add examples for the KV API

- docs/04-list-API.md
- docs/05-set-API.md
- docs/06-map-API.md
- docs/07-btree-API.md
- docs/08-attribute-API.md
- Attributes 관련 내용을 수정합니다.
- Collection API 문서에서 따로 설명되었던 attributes 생성 관련 내용을 attributes 문서로 이동시켰습니다. 
- 또한, KV API 형식에 맞춰 [설명] → [예시] 순으로 글의 구성이 변경되었습니다.
> DOC: Modify the attributes description

- docs/04-list-API.md
- list collection API의 예시를 변경합니다.
> DOC: Modify examples for the list document

- docs/04-list-API.md
- #321
- List API 수정에서 부족한 부분을 추가합니다.
> DOC: Add missing documentation for the list API

- docs/06-map-API.md
- map 아이템 관련 API 문서를 set과 유사한 형식으로 변경했습니다.
> DOC: Modify examples for the map document

- libmemcached/collection.cc
- #326
- smget_result 구조체를 bop_query 값에 따라 초기화하는 함수를 추가합니다.
> INTERNAL: Add a function to initialize a smget_result struct

- libmemcached/collection.cc
- #335
- Collection API에 있는 버전 체크를 mget과 동일하게 불필요한 라인을 제거합니다.
> INTERNAL: Remove unnecessary lines in collection API version check

- ChangeLog
- jam2in/arcus-works#708
- Changelog 형식을 수정합니다.
> DOC: Update ChangeLog format

- docs/02-arcus-c-client.md
-
- 앙상블 리스트 주소 예시를 변경합니다.
- "dev.arcuscloud.nhncorp.com:17288" -> "dev.arcuscloud.jam2in.com:2181"
> DOC: Change an ensemble address example

- .github/workflows/CI.yml
- #368 
- CI의 우분투 버전을 latest로 올립니다
> TEST: Upgrade the ubuntu version

- libmemcached/response.cc
- #367
- Ubuntu 22.04 변경 중 발생한 C Client의 컴파일 에러를 수정합니다.
```js
In function 'char* strncpy(char*, const char*, size_t)',
inlined from 'memcached_return_t textual_coll_smget_missed_key_fetch(memcached_server_write_instance_st, char*, memcached_coll_smget_result_st*)' at libmemcached/response.cc:2182:12:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:34: error: 'char* __builtin_strncpy(char*, const char*, long unsigned int)' output may be truncated copying between 0 and 4001 bytes from a string of length 4002 [-Werror=stringop-truncation]
95 |   return __builtin___strncpy_chk (__dest, __src, __len,
|          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
96 |                                   __glibc_objsize (__dest));
|                                   ~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
> INTERNAL: Fix a compile error in Ubuntu 22.04

- libmemcached/arcus.cc
- jam2in/arcus-works#508
- watcher event 발생 시 event type에 따라 로그를 기록하도록 합니다.
> INTERNAL: Log unexpected events received from ZooKeeper watch

- libmemcached/arcus.cc
> CLEANUP: Fix `ZOO_NOWATCHING_EVENT` to `ZOO_NOTWATCHING_EVENT`
